### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by LazyKernel** [kalmikko/digilog#1]
Code downloaded 26.4. 2.00am

## Usability
* My first intuition was to just add media but trying to add media straight away without first adding media types caused a crash. Possibly checking if the media type exists and showing an error message or just adding it if it doesn't exist could work.

* Kinda nitpicky, but I would personally like if you could use Y or y and N or n to add additional comments since nobody has time to press shift.

## Tests
* Personally using `assertEquals` in tests was more clear than `assertTrue` and when the tests inevitably fail I assume `assertEquals` gives nicer error messages than `assertTrue`. The format of `assertEquals` error messages is `expected <value>, actual <wrong value>`. It also works better with floating point numbers.

* Test coverage is quite low and it seems that the interface is not ignored when calculating the coverage. It does seem hard to separate interface code and actual program logic though so it might be worth to just test the text based interface anyway.

## Code 
* I tried if sql injection would work by trying to add a title with the name "test'); DROP TABLE Media;" and it seemed to break pretty much everything. It still does show the correct amount of titles (5) but when I try to list entries, it just throws and IllegalStateException with an error message `Caused by: org.h2.jdbc.JdbcSQLException: No data is available [2000-197]`.

* Code style feels heavy and it's not too easy to read. Personally I would add some newlines and spaces to make the code more airy and readable. Example pictures below

Current code: ![current](https://i.imgur.com/7qUi5tl.png)

Suggestion: ![suggestion](https://i.imgur.com/YfbKD59.png)

**Comment by kalmikko** [comment]
made a new text interface
